# -*- coding: utf-8 -*-
"""Build data/variant_map.tsv — the glyph normalisation table used by
core.normalize() (traditional -> simplified, variants -> standard form).

Build-time only: this script needs `zhconv` (pip install zhconv). The generated
TSV ships with the application, so the runtime has no extra dependency and the
normalisation is fully reproducible.

Only 1:1 single-character mappings are kept; context-sensitive merges
(e.g. 幹/乾 -> 干) are resolved by zhconv at the single-character level and are
documented as a known limitation.

The reference corpus is used as a blacklist: any source glyph that actually
occurs in the 82 frozen poems is dropped from the table. Those glyphs are scored
exactly as the study scored them, so normalisation can never move a published
figure. (Empirically this removes the variant-form merges — 峯/峰, 邨/村, 敎/教,
羣/群 … — while keeping the traditional -> simplified conversions.)
"""
import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'data', 'variant_map.tsv')

try:
    from zhconv import convert
except ImportError:
    sys.exit('zhconv is required to build the table: pip install zhconv')


def is_cjk(ch):
    o = ord(ch)
    return 0x4E00 <= o <= 0x9FFF or 0x3400 <= o <= 0x4DBF or 0xF900 <= o <= 0xFAFF


mapping = {}
for cp in list(range(0x4E00, 0xA000)) + list(range(0x3400, 0x4DC0)) + list(range(0xF900, 0xFB00)):
    src = chr(cp)
    dst = convert(src, 'zh-cn')
    if dst == src:
        continue
    if len(dst) != 1 or not is_cjk(dst):
        continue
    mapping[src] = dst

# never let the table point at itself or chain (keep it a single pass)
mapping = {k: v for k, v in mapping.items() if k != v}

# blacklist every glyph that occurs in the frozen reference corpus
used = set()
with open(os.path.join(HERE, '..', 'data', 'poems_82_text.csv'), encoding='utf-8-sig') as f:
    for r in csv.DictReader(f):
        used.update(r['text'])
dropped = {k: v for k, v in mapping.items() if k in used}
mapping = {k: v for k, v in mapping.items() if k not in used}
print('dropped (occurs in the 82-poem corpus): %d' % len(dropped))
for k in sorted(dropped)[:40]:
    print('   %s -> %s   [kept as written]' % (k, dropped[k]))

with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write('# glyph normalisation table (traditional -> simplified standard form)\n')
    f.write('# generated by tools/build_variant_map.py from zhconv (zh-cn)\n')
    f.write('# source glyphs occurring in the 82-poem frozen corpus are excluded,\n')
    f.write('# so normalisation can never alter a published figure.\n')
    f.write('# format: source<TAB>target\n')
    for k in sorted(mapping):
        f.write('%s\t%s\n' % (k, mapping[k]))

print('wrote %s: %d entries' % (OUT, len(mapping)))

# --- sanity checks ---------------------------------------------------------
sys.path.insert(0, os.path.join(HERE, '..', 'core'))
import gpdi

inv = gpdi.load_inventory()
hit_inv = [(c, mapping[c]) for c in inv if c in mapping]
print('inventory chars altered by the table: %d' % len(hit_inv))
for c, d in hit_inv[:20]:
    in_dst = 'in-inventory' if d in inv else '>>> NOT IN INVENTORY <<<'
    print('   %s -> %s  (%s)' % (c, d, in_dst))

texts = []
with open(os.path.join(HERE, '..', 'data', 'poems_82_text.csv'), encoding='utf-8-sig') as f:
    import csv
    for r in csv.DictReader(f):
        texts.append(r['text'])

changed = 0
for t in texts:
    n = ''.join(mapping.get(c, c) for c in t)
    if n != t:
        changed += 1
        print('   reference text changed:', t[:20], '->', n[:20])
print('reference texts altered by the table: %d / %d' % (changed, len(texts)))
